# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('dpi', models.IntegerField()),
                ('nit', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=40)),
            ],
        ),
    ]
